### ISSUE TITLE
Broken image URLs on Vagrant

### ISSUE THREAD

**Issue by dunn** [curationexperts/alexandria#657]
As of 60cbbb56e68bb64569b877c5efc7849be6c7e01c I'm still seeing issues on Vagrant when ingesting MODS (specifically the Rogers collection).  On a freshly provisioned Vagrant instance,
```
[adrl@localhost ~]$ cd /opt/alexandria-v2/current/
[adrl@localhost current]$ RAILS_ENV=production bin/ingest-mods /opt/ingest/metadata/adrl-dm/ingest-ready/hpamss032/collection/ /opt/ingest/data/images/hpamss032/
Loading environment...
Starting import...
Importing: /opt/ingest/metadata/adrl-dm/ingest-ready/hpamss032/collection//hpamss32-collection.xml
  Created Collection fk4qn6cb6h (HPA Mss 32)
Imported 1 records.
[adrl@localhost current]$ RAILS_ENV=production bin/ingest-mods /opt/ingest/metadata/adrl-dm/ingest-ready/hpamss032/objects/ /op
t/ingest/data/images/hpamss032/
Loading environment...
Starting import...
Importing: /opt/ingest/metadata/adrl-dm/ingest-ready/hpamss032/objects//hpamss32-carlrogersbwportrait-a-1.xml
  Attaching binary carlrogersbwportrait-a-1.tif
  Created Image fk4kw5nj2s (hpamss32-carlrogersbwportrait-a-1)
Importing: /opt/ingest/metadata/adrl-dm/ingest-ready/hpamss032/objects//hpamss32-carlrogersbwportrait-b-1.xml
  Attaching binary carlrogersbwportrait-b-1.tif
  Created Image fk4g73n41d (hpamss32-carlrogersbwportrait-b-1)
Imported 2 records.
```
results in broken URLs on all views:
![screen shot 2016-03-04 at 12 51 10 pm](https://cloud.githubusercontent.com/assets/985416/13539916/4966a0d8-e208-11e5-9643-0661a9b4d197.png)
![screen shot 2016-03-04 at 12 50 56 pm](https://cloud.githubusercontent.com/assets/985416/13539904/38dd2002-e208-11e5-897e-452426789291.png)

The image URLs look like
```
http://localhost/images/7d278t00k%2Ffiles%2F0bf0e95c-b711-4e91-bf4b-9ed108d66053/full/600,/0/default.jpg
```
and 
```
http://localhost/images/7d278t00k%2Ffiles%2F0bf0e95c-b711-4e91-bf4b-9ed108d66053/full/300,/0/default.jpg
```

**Comment by jcoyne** [comment]
What happens when you visit those URLs?

**Comment by jcoyne** [comment]
URLs like that work on the aws machine: http://ucsb.curationexperts.com/images/rx913p89r%2Ffiles%2Fae6fc0c7-ae31-46d0-b804-f47eb4518c87/full/300,/0/default.jpg

**Comment by dunn** [comment]
Oh, it's just that the port is missing.

**Comment by dunn** [comment]
The provisioner isn't setting `localhost_port` for https://github.com/curationexperts/alexandria-v2/blob/master/app/indexers/image_indexer.rb#L38

**Comment by dunn** [comment]
@acozine is `localhost_port` used by other projects? Should the fix for this be sent to `sufia-centos`?

**Comment by jcoyne** [comment]
Yeah, I don't understand why we need that. And I certainly don't understand why it is in secrets.

**Comment by jcoyne** [comment]
Can't that all be rolled into `Rails.application.config.host_name`?

**Comment by dunn** [comment]
You mean just tack the port onto `host_name`? That's fine with me; I think I just assumed `host_name` should be just the hostname without a port.

**Comment by dunn** [comment]
It might not work, actually; since the non-80 port (8484) is only on the host machine, setting `host_name = localhost:8484` causes ingests on the VM to fail:
```
[adrl@localhost current]$ RAILS_ENV=production bin/ingest-mods /opt/ingest/metadata/adrl-dm/ingest-ready/hpamss032/objects/ /opt/ingest/data/images/hpamss032/
Loading environment...
Starting import...
Importing: /opt/ingest/metadata/adrl-dm/ingest-ready/hpamss032/objects//hpamss32-carlrogersbwportrait-a-1.xml
/usr/local/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect': Failed to open TCP connection to localhost:8484 (Connection refused - connect(2) for "localhost" port 8484) (Errno::ECONNREFUSED)
        from /usr/local/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
        from /usr/local/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
        from /usr/local/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
        from /usr/local/lib/ruby/2.3.0/net/http.rb:878:in `connect'
        from /usr/local/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
        from /usr/local/lib/ruby/2.3.0/net/http.rb:852:in `start'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/resource.rb:51:in `get'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/rdf-1.99.1/lib/rdf/util/file.rb:95:in `open_url'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/rdf-1.99.1/lib/rdf/util/file.rb:320:in `open_file'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/rdf-1.99.1/lib/rdf/reader.rb:136:in `open'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/rdf-1.99.1/lib/rdf/mixin/mutable.rb:49:in `load'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/active-triples-0.7.5/lib/active_triples/rdf_source.rb:259:in `fetch'
        from /opt/alexandria-v2/releases/20160304221219/app/services/rdf/deep_indexing_service.rb:43:in `fetch_value'
        from /opt/alexandria-v2/releases/20160304221219/app/services/rdf/deep_indexing_service.rb:33:in `block (2 levels) in fetch_external'
        from /opt/alexandria-v2/releases/20160304221219/app/services/rdf/deep_indexing_service.rb:27:in `each'
        from /opt/alexandria-v2/releases/20160304221219/app/services/rdf/deep_indexing_service.rb:27:in `block in fetch_external'
        from /opt/alexandria-v2/releases/20160304221219/app/services/rdf/deep_indexing_service.rb:26:in `each'
        from /opt/alexandria-v2/releases/20160304221219/app/services/rdf/deep_indexing_service.rb:26:in `fetch_external'
        from /opt/alexandria-v2/releases/20160304221219/app/services/rdf/deep_indexing_service.rb:21:in `add_assertions'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/active-fedora-9.9.0/lib/active_fedora/rdf/indexing_service.rb:20:in `generate_solr_document'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/active-fedora-9.9.0/lib/active_fedora/indexing_service.rb:74:in `solrize_rdf_assertions'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/active-fedora-9.9.0/lib/active_fedora/indexing_service.rb:48:in `generate_solr_document'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/curation_concerns-models-0.10.0/app/services/curation_concerns/indexes_thumbnails.rb:14:in `generate_solr_document'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/curation_concerns-models-0.10.0/app/indexers/curation_concerns/work_indexer.rb:5:in `generate_solr_document'
        from /opt/alexandria-v2/releases/20160304221219/app/indexers/object_indexer.rb:21:in `generate_solr_document'
        from /opt/alexandria-v2/releases/20160304221219/app/indexers/image_indexer.rb:3:in `generate_solr_document'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/active-fedora-9.9.0/lib/active_fedora/indexing.rb:23:in `to_solr'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/curation_concerns-models-0.10.0/app/models/concerns/curation_concerns/human_readable_type.rb:11:in `to_solr'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/hydra-access-controls-9.8.1/app/models/concerns/hydra/access_controls/permissions.rb:15:in `to_solr'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/hydra-access-controls-9.8.1/app/models/concerns/hydra/access_controls/embargoable.rb:37:in `to_solr'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/active-fedora-9.9.0/lib/active_fedora/indexing.rb:32:in `update_index'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/active-fedora-9.9.0/lib/active_fedora/indexing.rb:61:in `update_record'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/active-fedora-9.9.0/lib/active_fedora/callbacks.rb:243:in `block (2 levels) in update_record'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:117:in `call'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/active-fedora-9.9.0/lib/active_fedora/callbacks.rb:243:in `block in update_record'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:117:in `call'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_update_callbacks'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/active-fedora-9.9.0/lib/active_fedora/callbacks.rb:242:in `update_record'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/active-fedora-9.9.0/lib/active_fedora/persistence.rb:141:in `create_or_update'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/active-fedora-9.9.0/lib/active_fedora/persistence.rb:31:in `save!'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/active-fedora-9.9.0/lib/active_fedora/validations.rb:56:in `save!'
        from /opt/alexandria-v2/releases/20160304221219/lib/importer/factory/object_factory.rb:39:in `block in update'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:117:in `call'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
        from /opt/alexandria-v2/releases/20160304221219/lib/importer/factory/object_factory.rb:38:in `update'
        from /opt/alexandria-v2/releases/20160304221219/lib/importer/factory/object_factory.rb:21:in `block in run'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `block in instrument'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `instrument'
        from /opt/alexandria-v2/releases/20160304221219/lib/importer/factory/object_factory.rb:19:in `run'
        from /opt/alexandria-v2/releases/20160304221219/lib/importer/mods_importer.rb:31:in `create_fedora_objects'
        from /opt/alexandria-v2/releases/20160304221219/lib/importer/mods_importer.rb:22:in `import'
        from /opt/alexandria-v2/releases/20160304221219/lib/importer/mods_importer.rb:13:in `block in import_all'
        from /opt/alexandria-v2/releases/20160304221219/lib/importer/mods_importer.rb:11:in `each'
        from /opt/alexandria-v2/releases/20160304221219/lib/importer/mods_importer.rb:11:in `import_all'
        from bin/ingest-mods:31:in `<main>'

**Comment by jcoyne** [comment]
Do you have the web server up and running at that address when you do the ingest?

**Comment by dunn** [comment]
Yeah. On the guest VM, it's running at `localhost:80`, which is forwarded to `localhost:8484` on the host by Vagrant.  So for most operations the port needs to be `80` or unset, but for indexing images and other files it needs to be `8484`.
